# Complete Virtual Teams Database
VIRTUAL_TEAMS = {
    "Premier League": {
        "Man City": {"power": 92, "star": "E. Haaland"},
        "Arsenal": {"power": 89, "star": "B. Saka"},
        "Liverpool": {"power": 88, "star": "M. Salah"},
        "Chelsea": {"power": 85, "star": "C. Palmer"},
        "Tottenham": {"power": 83, "star": "H. Son"},
        "Man United": {"power": 82, "star": "B. Fernandes"},
        "Newcastle": {"power": 81, "star": "A. Isak"},
        "Aston Villa": {"power": 80, "star": "O. Watkins"},
        "West Ham": {"power": 78, "star": "J. Bowen"},
        "Brighton": {"power": 77, "star": "K. Mitoma"},
        "Crystal Palace": {"power": 76, "star": "E. Eze"},
        "Fulham": {"power": 75, "star": "A. Robinson"},
        "Bournemouth": {"power": 74, "star": "D. Solanke"},
        "Wolves": {"power": 73, "star": "P. Neto"},
        "Everton": {"power": 74, "star": "J. Pickford"},
        "Brentford": {"power": 75, "star": "I. Toney"},
        "Nott'm Forest": {"power": 73, "star": "M. Gibbs-White"},
        "Leicester": {"power": 72, "star": "K. Dewsbury-Hall"},
        "Southampton": {"power": 71, "star": "A. Armstrong"},
        "Ipswich Town": {"power": 70, "star": "C. Chaplin"},
    },
    "La Liga": {
        "Real Madrid": {"power": 93, "star": "K. Mbappe"},
        "Barcelona": {"power": 88, "star": "R. Lewandowski"},
        "Atletico Madrid": {"power": 85, "star": "A. Griezmann"},
        "Girona": {"power": 80, "star": "A. Dovbyk"},
        "Real Sociedad": {"power": 79, "star": "M. Oyarzabal"},
        "Athletic Club": {"power": 78, "star": "I. Williams"},
        "Real Betis": {"power": 77, "star": "I. Isco"},
        "Villarreal": {"power": 76, "star": "G. Moreno"},
        "Valencia": {"power": 75, "star": "H. Duro"},
        "Osasuna": {"power": 74, "star": "A. Budimir"},
        "Getafe": {"power": 73, "star": "B. Mayoral"},
        "Celta Vigo": {"power": 74, "star": "I. Aspas"},
        "Sevilla": {"power": 75, "star": "Y. En-Nesyri"},
        "Mallorca": {"power": 73, "star": "V. Muriqi"},
        "Alaves": {"power": 72, "star": "S. Omorodion"},
        "Las Palmas": {"power": 72, "star": "K. Rodriguez"},
        "Rayo Vallecano": {"power": 71, "star": "I. Palazon"},
        "Leganes": {"power": 70, "star": "M. Garcia"},
        "Real Valladolid": {"power": 69, "star": "S. Sylla"},
        "Espanyol": {"power": 71, "star": "J. Puado"},
    },
    "Serie A": {
        "Inter Milan": {"power": 88, "star": "L. Martinez"},
        "AC Milan": {"power": 85, "star": "R. Leao"},
        "Juventus": {"power": 84, "star": "D. Vlahovic"},
        "Napoli": {"power": 82, "star": "V. Osimhen"},
        "AS Roma": {"power": 81, "star": "P. Dybala"},
        "Atalanta": {"power": 80, "star": "G. Scamacca"},
        "Lazio": {"power": 79, "star": "M. Zaccagni"},
        "Fiorentina": {"power": 78, "star": "N. Gonzalez"},
        "Torino": {"power": 77, "star": "D. Zapata"},
        "Bologna": {"power": 79, "star": "J. Zirkzee"},
        "Monza": {"power": 75, "star": "M. Pessina"},
        "Genoa": {"power": 74, "star": "A. Gudmundsson"},
        "Lecce": {"power": 73, "star": "N. Krstovic"},
        "Udinese": {"power": 74, "star": "L. Samardzic"},
        "Hellas Verona": {"power": 72, "star": "T. Noslin"},
        "Cagliari": {"power": 71, "star": "Z. Luvumbo"},
        "Empoli": {"power": 70, "star": "N. Cambiaghi"},
        "Parma": {"power": 71, "star": "D. Man"},
        "Como": {"power": 70, "star": "P. Cutrone"},
        "Venezia": {"power": 69, "star": "J. Pohjanpalo"},
    },
    "Bundesliga": {
        "Bayern Munich": {"power": 90, "star": "H. Kane"},
        "B. Leverkusen": {"power": 88, "star": "F. Wirtz"},
        "Borussia Dortmund": {"power": 85, "star": "J. Brandt"},
        "RB Leipzig": {"power": 84, "star": "X. Simons"},
        "VfB Stuttgart": {"power": 82, "star": "S. Guirassy"},
        "Eintracht Frankfurt": {"power": 79, "star": "O. Marmoush"},
        "SC Freiburg": {"power": 78, "star": "V. Grifo"},
        "Hoffenheim": {"power": 77, "star": "M. Beier"},
        "Werder Bremen": {"power": 75, "star": "M. Ducksch"},
        "FC Heidenheim": {"power": 74, "star": "T. Kleindienst"},
        "FC Augsburg": {"power": 73, "star": "E. Demirovic"},
        "VfL Wolfsburg": {"power": 75, "star": "J. Wind"},
        "Mainz 05": {"power": 74, "star": "J. Burkardt"},
        "Bor. M'gladbach": {"power": 76, "star": "A. Plea"},
        "Union Berlin": {"power": 75, "star": "R. Gosens"},
        "VfL Bochum": {"power": 72, "star": "T. Asano"},
        "St. Pauli": {"power": 70, "star": "M. Irvine"},
        "Holstein Kiel": {"power": 69, "star": "S. Skrzybski"},
    },
    "Ligue 1": {
        "PSG": {"power": 89, "star": "O. Dembele"},
        "Monaco": {"power": 82, "star": "W. Ben Yedder"},
        "Brest": {"power": 80, "star": "R. Del Castillo"},
        "Lille": {"power": 81, "star": "J. David"},
        "Nice": {"power": 79, "star": "T. Moffi"},
        "Lyon": {"power": 78, "star": "A. Lacazette"},
        "Lens": {"power": 80, "star": "F. Sotoca"},
        "Marseille": {"power": 81, "star": "P. Aubameyang"},
        "Reims": {"power": 76, "star": "O. Diakite"},
        "Rennes": {"power": 77, "star": "A. Kalimuendo"},
        "Toulouse": {"power": 75, "star": "T. Dallinga"},
        "Montpellier": {"power": 74, "star": "T. Savanier"},
        "Strasbourg": {"power": 73, "star": "E. Emegha"},
        "Nantes": {"power": 72, "star": "M. Mohamed"},
        "Le Havre": {"power": 71, "star": "M. Bayo"},
        "Auxerre": {"power": 70, "star": "G. Hein"},
        "Angers": {"power": 69, "star": "L. Diony"},
        "Saint-Etienne": {"power": 71, "star": "I. Sissoko"},
    },
    "Saudi Pro League": {
        "Al Hilal": {"power": 82, "star": "Neymar Jr."},
        "Al Nassr": {"power": 81, "star": "C. Ronaldo"},
        "Al Ahli": {"power": 79, "star": "R. Mahrez"},
        "Al Ittihad": {"power": 80, "star": "K. Benzema"},
        "Al Taawoun": {"power": 74, "star": "M. Barrow"},
        "Al Ettifaq": {"power": 75, "star": "M. Dembele"},
        "Al Fateh": {"power": 73, "star": "C. Tello"},
        "Al Shabab": {"power": 74, "star": "Y. Carrasco"},
        "Al Fayha": {"power": 71, "star": "F. Sakala"},
        "Damac": {"power": 72, "star": "G. N'Koudou"},
        "Al Khaleej": {"power": 70, "star": "F. Martins"},
        "Al Raed": {"power": 69, "star": "J. Tavares"},
        "Al Wehda": {"power": 71, "star": "O. Ighalo"},
        "Al Riyadh": {"power": 68, "star": "K. Musona"},
        "Al Okhdood": {"power": 67, "star": "F. Tanase"},
        "Al Qadsiah": {"power": 73, "star": "P. Aubameyang"},
    },
    "MLS (USA)": {
        "Inter Miami": {"power": 77, "star": "L. Messi"},
        "Columbus Crew": {"power": 75, "star": "C. Hernandez"},
        "LAFC": {"power": 74, "star": "D. Bouanga"},
        "FC Cincinnati": {"power": 74, "star": "L. Acosta"},
        "LA Galaxy": {"power": 73, "star": "R. Puig"},
        "Real Salt Lake": {"power": 72, "star": "C. Arango"},
        "NY Red Bulls": {"power": 71, "star": "E. Forsberg"},
        "Orlando City": {"power": 72, "star": "F. Torres"},
        "Seattle Sounders": {"power": 73, "star": "J. Morris"},
        "Atlanta United": {"power": 71, "star": "T. Almada"},
        "Philadelphia Union": {"power": 72, "star": "D. Gazdag"},
        "NYCFC": {"power": 70, "star": "S. Rodriguez"},
        "Portland Timbers": {"power": 71, "star": "Evander"},
        "Houston Dynamo": {"power": 70, "star": "H. Herrera"},
    },
    "World Cup": {
        "Argentina": {"power": 92, "star": "L. Messi"},
        "France": {"power": 91, "star": "K. Mbappe"},
        "Brazil": {"power": 89, "star": "Vini Jr."},
        "England": {"power": 88, "star": "J. Bellingham"},
        "Spain": {"power": 87, "star": "L. Yamal"},
        "Germany": {"power": 86, "star": "F. Wirtz"},
        "Portugal": {"power": 85, "star": "C. Ronaldo"},
        "Netherlands": {"power": 84, "star": "V. van Dijk"},
        "Italy": {"power": 83, "star": "N. Barella"},
        "Belgium": {"power": 82, "star": "K. De Bruyne"},
        "Uruguay": {"power": 83, "star": "F. Valverde"},
        "Croatia": {"power": 81, "star": "L. Modric"},
        "USA": {"power": 78, "star": "C. Pulisic"},
        "Mexico": {"power": 77, "star": "S. Gimenez"},
        "Colombia": {"power": 80, "star": "L. Diaz"},
        "Japan": {"power": 77, "star": "K. Mitoma"},
    },
    "AFCON": {
        "Senegal": {"power": 81, "star": "S. Mane"},
        "Morocco": {"power": 82, "star": "A. Hakimi"},
        "Nigeria": {"power": 80, "star": "V. Osimhen"},
        "Ivory Coast": {"power": 79, "star": "S. Haller"},
        "Egypt": {"power": 78, "star": "M. Salah"},
        "Algeria": {"power": 77, "star": "R. Mahrez"},
        "Cameroon": {"power": 76, "star": "A. Onana"},
        "Ghana": {"power": 75, "star": "M. Kudus"},
        "Mali": {"power": 74, "star": "Y. Bissouma"},
        "South Africa": {"power": 73, "star": "P. Tau"},
        "DR Congo": {"power": 74, "star": "C. Mbemba"},
        "Burkina Faso": {"power": 72, "star": "E. Tapsoba"},
        "Guinea": {"power": 73, "star": "S. Guirassy"},
        "Cape Verde": {"power": 71, "star": "Bebe"},
    },
}
